-- Mamdani on Tiger Data (TimescaleDB).
-- issues:   one row per real-world problem (deduplicated)
-- reports:  every citizen submission — a hypertable, because this is the city's time-series memory
-- media:    evidence photos
-- report_sessions: phone shutter presses, so a retried submission never creates a second report
-- reports_hourly: continuous aggregate powering the Command Center's activity chart

create extension if not exists timescaledb;
create extension if not exists pgcrypto;

create table if not exists issues (
  id                bigint generated by default as identity (start with 1831) primary key,
  category          text not null,
  title             text not null,
  summary           text not null default '',
  lat               double precision not null,
  lng               double precision not null,
  address           text not null default '',
  severity          int not null,
  safety_risk       int not null,
  hazards           jsonb not null default '[]',
  accessibility     jsonb not null,
  department        text not null,
  status            text not null default 'new',
  reports           int not null default 1,
  first_reported_at timestamptz not null default now(),
  last_reported_at  timestamptz not null default now(),
  resolved_at       timestamptz,
  media_id          uuid,
  box               jsonb,
  events            jsonb not null default '[]',
  updated_at        timestamptz not null default now()
);
create index if not exists issues_open_geo on issues (category, lat, lng) where status <> 'resolved';
create index if not exists issues_updated on issues (updated_at);

create table if not exists reports (
  id          uuid not null default gen_random_uuid(),
  issue_id    bigint not null,
  created_at  timestamptz not null default now(),
  lat         double precision not null,
  lng         double precision not null,
  address     text not null default '',
  media_id    uuid,
  transcript  text not null default '',
  category    text not null,
  analysis    jsonb not null,
  primary key (id, created_at)
);
select create_hypertable('reports', by_range('created_at', interval '1 day'), if_not_exists => true);
create index if not exists reports_issue on reports (issue_id, created_at desc);

create table if not exists media (
  id         uuid primary key default gen_random_uuid(),
  mime       text not null,
  data       bytea not null,
  created_at timestamptz not null default now()
);

-- one row per shutter press from the phone: the idempotency key that guarantees one commit
create table if not exists report_sessions (
  session_id   text primary key,
  issue_id     bigint,
  response     jsonb,
  created_at   timestamptz not null default now(),
  completed_at timestamptz
);

create materialized view if not exists reports_hourly
with (timescaledb.continuous, timescaledb.materialized_only = false) as
  select time_bucket(interval '1 hour', created_at) as bucket, category, count(*) as n
  from reports
  group by 1, 2
with no data;

select add_continuous_aggregate_policy('reports_hourly',
  start_offset => interval '3 days',
  end_offset => interval '1 hour',
  schedule_interval => interval '5 minutes',
  if_not_exists => true);
